export const RESET_INVENTORY = 'RESET_INVENTORY'
export const SET_INVENTORY = 'SET_INVENTORY'
export const SET_SELECTION = 'SET_INVENTORY_SELECTION'
export const SET_REQUEST_STATUS = 'SET_REQUEST_STATUS'
export const ADD_ITEM_TO_INVENTORY = 'ADD_ITEM_TO_INVENTORY'
export const REMOVE_ITEM_FROM_INVENTORY = 'REMOVE_ITEM_FROM_INVENTORY'

export default {
  RESET_INVENTORY,
  SET_INVENTORY,
  SET_SELECTION,
  SET_REQUEST_STATUS,
  ADD_ITEM_TO_INVENTORY,
  REMOVE_ITEM_FROM_INVENTORY,
}
